### ISSUE TITLE
fileName not defined

### ISSUE THREAD

**Issue by Faleij** [YaroslavGaponov/node-jvm#26]
```
DEBUG: loading ./stagger.jar@se/su/ling/stagger/CTBTagger.class ...
\stagger\node_modules\node-jvm\libs\classes.js:52
            this.loadClassFile(path.dirname(fileName) + path.sep + classes[i] + ".class");
                                            ^

ReferenceError: fileName is not defined
    at Classes.loadClassBytes (\stagger\node_modules\node-jvm\libs\classes.js:52:45)
    at \stagger\node_modules\node-jvm\libs\classes.js:85:22
    at Array.forEach (native)
    at Classes.loadJarFile (\stagger\node_modules\node-jvm\libs\classes.js:81:16)
    at JVM.loadJarFile (\stagger\node_modules\node-jvm\libs\jvm.js:81:20)
    at Object.<anonymous> (\stagger\run.js:4:31)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by YaroslavGaponov** [comment]
I can't reproduce this situation. May be problem in stagger.jar

**Comment by Faleij** [comment]
ah, npm installed files does not match master on github although they have the same version
