### ISSUE TITLE
error when run examples

### ISSUE THREAD

**Issue by argan** [YaroslavGaponov/node-jvm#34]
ENV:  node --version  : v12.8.1

--------ERROR MESSAGES-----
./fibonacci.js

/Users/***/Labs/node-jvm/libs/logger.js:32
        util.debug(msg);
             ^

TypeError: util.debug is not a function
    at module.exports.Logger.debug (/Users/argan/Labs/node-jvm/libs/logger.js:32:14)
    at module.exports.Classes.loadClassFile (/Users/argan/Labs/node-jvm/libs/classes.js:53:9)
    at module.exports.JVM.loadClassFile (/Users/argan/Labs/node-jvm/libs/jvm.js:56:20)
    at /Users/argan/Labs/node-jvm/libs/jvm.js:68:22
    at Array.forEach (<anonymous>)
    at module.exports.JVM.loadClassFiles (/Users/argan/Labs/node-jvm/libs/jvm.js:63:11)
    at Object.<anonymous> (/Users/argan/Labs/node-jvm/examples/fibonacci/fibonacci.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)

**Comment by YaroslavGaponov** [comment]
https://github.com/YaroslavGaponov/node-jvm/commit/19d989142d023a4eca7be69fcdb5ed6b6985eaf1
